### ISSUE TITLE
`/recommend` and `/project` pages style be affected

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/dannypsnl.github.io#53]
TODO:
1. let title `margin-top` be 0 in these pages
    ```css
    h1 {
      margin-top: 0;
    }
    ```
2. misc?
